### PR TITLE
Fixed illegal mix of collations for operation 'concat'

### PR DESCRIPTION
**Pull request by kamaroly**
Fixed illegal mix of collations for operation 'concat' error and SET GLOBAL log_bin_trust_function_creators = 1;

### CODE REVIEW

**Comment by theory** [comment]
Hey @ hepabolu, looks like you're closer to maintaining this beast than I am. Does this PR look sensible to you? Would you like to take over mytap?

**Comment by kamaroly** [comment]
Yes, I would love to take it over

**Comment by theory** [comment]
Sorry, meant that for @hepabolu, whose [fork](/hepabolu/mytap) is *miles* ahead of mine.

**Comment by hepabolu** [comment]
@theory I'd love to, but I'd like to be a good github citizen so any offline help is greatly appreciated.

**Comment by theory** [comment]
> @theory I'd love to, but I'd like to be a good github citizen so any offline help is greatly appreciated.

Sorry @hepabolu, not sure I follow. Point is that I don't have the time or inclination to maintain myTAP, and it looks like you do. I could transfer ownership to you.

**Comment by hepabolu** [comment]
@kamaroly Can you provide some tests that would fail without your fix and pass with your fix?

**Comment by animalcarpet** [comment]
Closing this as the error has not been reproduced.

**Pull request closed without merging**
